import Head from 'next/head';
import Image from 'next/image';
import { homeStyles } from '../styles/home';

export default function Home() {
  return (
    <div css={homeStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={homeStyles.main}>
        {/* component for adding event */}
        {/* component for rendering all events */}
      </main>
    </div>
  );
}
